# Use a node base image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./
RUN npm install

# Copy the rest of the application files
COPY . .  
# Expose the port the app will run on
EXPOSE 3000

# Command to run the backend
CMD ["npm", "run", "start-backend"]
