FROM node:20
RUN node -v

# Set the working directory inside the container
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy the frontend source code into the container
COPY . . 

# Expose the React app port
EXPOSE 5173

# Start the frontend React app
CMD ["npm", "run", "dev"]
